# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/103GOn6F-5HlXIXvMyeMsYq_39HdLMn0I
"""
__version__ = "0.0.1"
